version: "3.9"
services:
  php-fpm:
    build: 
      context: ./php-fpm
      dockerfile: ./php-fpm.dockerfile
      labels:
        - com.nolan.description=php-fpm with development requirements
        - com.nolan.author=nolan
    image: php-fpm:local
    container_name: php-fpm
    profiles:
      - web
    restart: always
    networks:
      - web
    volumes:
      - ./logs:/var/log
      - ./logs:/data/logs
      - ${PHP_HOME}:/data/php
    ports:
      - "9001:9001"