# docker-compose up

version: "3.9"
services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    profiles:
      - web
    restart: always
    volumes:
      - ./nginx:/etc/nginx
      - ./logs:/var/log
      - ${PHP_HOME}:/data/php
    ports:
      - "80"
    networks:
      - web
  php-fpm:
    image: php-fpm:meicai
    container_name: php-fpm
    profiles:
      - web
    restart: always
    networks:
      - web
    volumes:
      - ./logs:/var/log
      - ./logs:/data/l80:ogs
      - ${PHP_HOME}:/data/php
    ports:
      - "9001:9001"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: elasticsearch
    profiles:
      - "es"
    networks:
      - web
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "/data/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=elastic
networks:
  web:
    driver: bridge